version: 2
jobs:
  build:
    machine: true
    working_directory: ~/serverless-plugin-stackstorm
    steps:
      - checkout
      - run:
          name: Switch to supported version of Node
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install 8.4.0 && nvm alias default 8.4.0

            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - run:
          name: Install libstdc++
          command: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install libstdc++-4.9-dev
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install the package
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm test
      - run:
          name: Build test container
          command: docker build -t slstest tests/e2e/service/container
      - run:
          name: Run integration tests
          command: npm run integration
