version: 2
jobs:
  build:
    working_directory: ~/serverless-plugin-stackstorm
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install the package
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
  python_build:
    working_directory: ~/serverless-plugin-stackstorm
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Install Python test dependencies
          command: pip install -r requirements-test.txt
      - run:
          name: Python Lint (flake8)
          command: flake8 --config ./lint-configs/python/.flake8 stackstorm/handler.py
      - run:
          name: Python Lint (pylint)
          command: pylint -E --rcfile=./lint-configs/python/.pylintrc stackstorm/handler.py
