version: 2
jobs:
  build:
    working_directory: ~/serverless-plugin-stackstorm
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install the package
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm test
      - setup_remote_docker
      - run:
          name: Build test container
          command: docker build -t slstest tests/e2e/service/container
      - run:
          name: Run integration tests
          command: npm run integration
